org: letguilhermec
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

params:
  default:
    dbName: alura-serverless
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}
    salt: AGpiuqagjklg)@*aosigha0a8wghy
  prod:

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DBNAME: ${param:dbName}
    SALT: ${param:salt}

functions:
  sendResponse:
    handler: api/index.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
  getResult:
    handler: api/index.getResult
    events:
      - httpApi:
          path: /api/results/{id}
          method: get

plugins:
  - serverless-offline
