org: letguilhermec
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

params:
  default:
    dbName: alura-serverless
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}
    salt: AGpiuqagjklg)@*aosigha0a8wghy
    jwtSecret: IS50EhUm4StR!NGagh0-9uq324oihga;lskjkg30948yoidaffghjl;ajknsfg;oiau
  prod:

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DBNAME: ${param:dbName}
    SALT: ${param:salt}
    JWT_SECRET: ${param:jwtSecret}

functions:
  sendResponse:
    handler: api/index.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/index.getResult
    events:
      - httpApi:
          path: /api/results/{id}
          method: get
  login:
    handler: api/index.login
    events:
      - httpApi:
          path: /api/login
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/login.json)}

plugins:
  - serverless-offline
